sonar.projectKey=swirlit:indezy
sonar.projectName=Indezy
sonar.sourceEncoding=UTF-8
sonar.sources=indezy-server/src/main,indezy-web/src
sonar.tests=indezy-server/src/test,indezy-web/e2e
sonar.java.binaries=indezy-server/target/classes
sonar.java.libraries=.cache/maven/**/*.jar
sonar.coverage.jacoco.xmlReportPaths=indezy-server/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=indezy-web/coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**,**/*.config.ts,**/environment*.ts,**/*.spec.ts
sonar.test.inclusions=**/*Test.java,**/*Tests.java,**/*.spec.ts
sonar.coverage.exclusions=**/config/**,**/dto/**,**/model/**,**/*Application.java,indezy-web/src/main.ts
sonar.scm.provider=git
