apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: indezy
  namespace: infrastructure
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/chefzaid/indezy.git
    targetRevision: main
    path: deployments
  destination:
    server: https://kubernetes.default.svc
    namespace: application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
