apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - indezy-secrets.yaml
  - indezy-db-setup.yaml
  - indezy-server.yaml
  - indezy-web.yaml
  - indezy-ingress.yaml
images:
  - name: registry.swirlit.dev/root/indezy/indezy-server
    newTag: initial
  - name: registry.swirlit.dev/root/indezy/indezy-web
    newTag: initial
